project_id = "fwmzeaztjxrxxzxzxmgc"

[functions.nf-import-xml]
verify_jwt = true

[functions.nf-consultar-sefaz]
verify_jwt = true

[functions.copiloto-acoes-chat]
verify_jwt = true

[functions.copiloto-acoes-transcrever]
verify_jwt = true

[functions.copiloto-acoes-criar]
verify_jwt = true

[functions.copiloto-acoes-analise]
verify_jwt = true
