DELETE FROM public.stg_mapa_de_para_contabil_financeiro;
DELETE FROM public.stg_mapa_de_para_bancos_pacote02;
DELETE FROM public.stg_sugestoes_novas_contas;
DELETE FROM public.stg_pendencias_de_para;
DELETE FROM public.stg_plano_contas_proposto;
DELETE FROM public.stg_mapa_de_para_orcamento_contratos;
DELETE FROM public.stg_aprovacao_contas;
-- PACOTE 02 — DML carga staging

-- 20_stg_mapa_de_para_contabil_financeiro.csv -> stg_mapa_de_para_contabil_financeiro (358 linhas)
INSERT INTO public.stg_mapa_de_para_contabil_financeiro (id_de_para,origem_base,arquivo_origem,chave_de_para,tipo_movimento,classificacao_original,contexto_gerencial,categoria_despesa_top,empresas_detectadas_top,centros_custo_top,bancos_top,qtd_linhas_afetadas,qtd_valor_valido,valor_total,valor_abs_total,codigo_evento_sugerido,descricao_evento_sugerido,conta_debito_codigo_sugerida,conta_debito_nome_sugerida,conta_debito_origem,conta_credito_codigo_sugerida,conta_credito_nome_sugerida,conta_credito_origem,conta_resultado_ref_codigo,conta_resultado_ref_nome,conta_resultado_ref_origem,ids_sugestoes_contas_relacionadas,tipo_gerencial,direto_indireto,fixo_variavel,impacta_caixa,impacta_dre_competencia,impacta_dre_caixa,impacta_balanco,gera_partida_caixa,gera_competencia_estimada,grau_confianca,status_de_para,pendencia,exemplos_historico,observacao_migracao) VALUES
('DP-FIN-00001','FINANCEIRO_REALIZADO','Bd_Fluxo_de Caixa_Atualizado_04.csv','FINANCEIRO_REALIZADO|ENTRADA|ALUGUEL|ADMINISTRATIVO_INDIRETO','ENTRADA','ALUGUEL','ADMINISTRATIVO_INDIRETO',NULL,'AGPS:1','ADMINISTRATIVO:1','BANRI AGPS:1',1,1,2500.00,2500.00,'EVT-014','Entrada de caixa a classificar','DYNAMIC_BANK','Conta bancária conforme campo Banco','DINAMICA','04.2.3.03.04.004','Outras Receitas','PLANO_CONTAS_ORIGINAL','04.2.3.03.04.004','Outras Receitas','PLANO_CONTAS_ORIGINAL',NULL,'RECEITA_OUTRAS','INDIRETO','FIXO','SIM','DEPENDE','SIM','SIM','SIM','NAO','BAIXA','GERADO_IA_REVISAR','Entrada não mapeada por regra específica.','ALUGUEL CASA CAPÃO ( ALEXIA GOLDANI)','De-para agregado por classificação/tipo/contexto. No lançamento final, banco e centro de custo serão aplicados por linha.'),
('DP-FIN-00002','FINANCEIRO_REALIZADO','Bd_Fluxo_de Caixa_Atualizado_04.csv','FINANCEIRO_REALIZADO|ENTRADA|APLICAÇÃO|ADMINISTRATIVO_INDIRETO','ENTRADA','APLICAÇÃO','ADMINISTRATIVO_INDIRETO','ÚNICA:11','HAGG:5 | NH:3 | AGPS:2 | SN:2','MOVIMENTAÇÕES FINANC.:11 | ADMINISTRATIVO:1','BB HAGG- APLICAÇÃO:3 | BANRI NH- APLICAÇÃO:3 | BANRI AGPS - APLICAÇÃO:2 | BANRI SN- APLICAÇÃO:2 | CDB INTER:1 | BANRI HAGG- APLICAÇÃO:1',12,12,894349.20,894349.20,'EVT-014','Aplicação financeira','01.1.1.03.99.002','Aplicações financeiras de liquidez imediata - demais bancos','SUGESTAO_NOVA_CONTA','DYNAMIC_BANK','Conta bancária conforme campo Banco','DINAMICA',NULL,NULL,NULL,'SUG-00001','ATIVO_FINANCEIRO','NAO_APLICAVEL','NAO_APLICAVEL','SIM','NAO','NAO','SIM','SIM','NAO','MEDIA','AGUARDANDO_APROVACAO_CONTA','Aprovar conta patrimonial de aplicações por banco ou genérica.','APLICAÇÃO CDB || APLICAÇÃO BB CDB || CDB INTER','De-para agregado por classificação/tipo/contexto. No lançamento final, banco e centro de custo serão aplicados por linha.')