-- =========================================================================
-- JURÍDICO — Processos: PK no surrogate id (identity); "ID" vira coluna comum
--
-- A tabela veio do Flask com a PRIMARY KEY na coluna legada "ID" (maiúscula),
-- mas o modelo é "1 linha por motivo": o mesmo processo aparece em várias
-- linhas com o mesmo "ID" (e os processos novos vêm com "ID" NULL). Logo "ID"
-- não pode ser PK. A PK real é a coluna id (minúscula, identity) — que é por
-- onde o app ordena/deduplica (Processos.tsx). Sem isso, a carga do histórico
-- (seed) estourava com duplicate key / null em id.
--
-- Passos (idempotentes):
--   1. Garante a coluna surrogate id.
--   2. Backfill de ids nulos (ordem qualquer — é só surrogate).
--   3. Remove a PRIMARY KEY que estiver em "ID" (mantém se já estiver em id).
--   4. "ID" vira coluna comum (anulável; CSV tem repetidos e NULL).
--   5. Garante id NOT NULL + GENERATED BY DEFAULT AS IDENTITY.
--   6. Define id como PRIMARY KEY.
--   7. Reposiciona a sequência da identity acima do maior id.
--   8. Reafirma RLS/grants/policy e recarrega o PostgREST (sem o reload a tela
--      fica vazia: o load() engole o erro do schema cache velho).
-- =========================================================================

DO $$
DECLARE
  v_pk   text;
  v_base bigint;
  v_max  bigint;
BEGIN
  IF to_regclass('public."JUR_PROCESSOS"') IS NULL THEN
    RETURN;
  END IF;

  -- 1) Coluna surrogate id.
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='JUR_PROCESSOS' AND column_name='id'
  ) THEN
    EXECUTE 'ALTER TABLE public."JUR_PROCESSOS" ADD COLUMN id bigint';
  END IF;

  -- 2) Backfill de ids nulos (acima do maior id já existente).
  SELECT COALESCE(max(id), 0) INTO v_base FROM public."JUR_PROCESSOS" WHERE id IS NOT NULL;
  EXECUTE format($f$
    UPDATE public."JUR_PROCESSOS" p
       SET id = s.rn
      FROM (
        SELECT ctid, %s + row_number() OVER (ORDER BY ctid) AS rn
          FROM public."JUR_PROCESSOS" WHERE id IS NULL
      ) s
     WHERE p.ctid = s.ctid
  $f$, v_base);

  -- 3) Remove a PRIMARY KEY atual se ela NÃO for exatamente (id).
  SELECT conname INTO v_pk FROM pg_constraint
   WHERE conrelid='public."JUR_PROCESSOS"'::regclass AND contype='p';
  IF v_pk IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM pg_constraint con
    JOIN pg_attribute a ON a.attrelid=con.conrelid AND a.attnum = ANY (con.conkey)
    WHERE con.conname=v_pk AND con.conrelid='public."JUR_PROCESSOS"'::regclass
      AND a.attname='id' AND array_length(con.conkey,1)=1
  ) THEN
    EXECUTE format('ALTER TABLE public."JUR_PROCESSOS" DROP CONSTRAINT %I', v_pk);
  END IF;

  -- 4) "ID" legado vira coluna comum, anulável.
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='JUR_PROCESSOS' AND column_name='ID'
  ) THEN
    EXECUTE 'ALTER TABLE public."JUR_PROCESSOS" ALTER COLUMN "ID" DROP NOT NULL';
  END IF;

  -- 5) id NOT NULL + IDENTITY.
  EXECUTE 'ALTER TABLE public."JUR_PROCESSOS" ALTER COLUMN id SET NOT NULL';
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='JUR_PROCESSOS'
      AND column_name='id' AND is_identity='YES'
  ) THEN
    EXECUTE 'ALTER TABLE public."JUR_PROCESSOS" ALTER COLUMN id DROP DEFAULT';
    EXECUTE 'ALTER TABLE public."JUR_PROCESSOS" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;

  -- 6) id como PRIMARY KEY (se ainda não houver PK).
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid='public."JUR_PROCESSOS"'::regclass AND contype='p'
  ) THEN
    EXECUTE 'ALTER TABLE public."JUR_PROCESSOS" ADD PRIMARY KEY (id)';
  END IF;

  -- 7) Sequência da identity acima do maior id (evita colisão em INSERT futuro).
  SELECT COALESCE(max(id), 0) INTO v_max FROM public."JUR_PROCESSOS";
  PERFORM setval(pg_get_serial_sequence('public."JUR_PROCESSOS"','id'), v_max + 1, false);
END $$;

-- 8) Reafirma RLS/grants/policy (mesmo padrão da 016) e recarrega o PostgREST.
ALTER TABLE public."JUR_PROCESSOS" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."JUR_PROCESSOS" TO authenticated;
DROP POLICY IF EXISTS "JUR_PROCESSOS_all_auth" ON public."JUR_PROCESSOS";
CREATE POLICY "JUR_PROCESSOS_all_auth" ON public."JUR_PROCESSOS"
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

NOTIFY pgrst, 'reload schema';
