-- =========================================================================
-- JURÍDICO — Sistema de Processos (tabelas migradas do sistema Flask)
--
-- Tabelas (já migradas para o banco): SISTEMA_JURIDICORT (1 linha por motivo,
-- agrupadas por numero_processo), SISTEMA_JURIDICORT_dort (catálogo DORT) e
-- SISTEMA_JURIDICO_COMENTARIOS (comentários por processo).
--
-- Aqui só configuramos acesso via PostgREST: RLS + grants + policies.
--   • Leitura: qualquer autenticado (a tela é gated no front p/ o Jurídico).
--   • Escrita: somente Jurídico Trabalhando (função is_juridico_ativo()).
-- is_juridico_ativo() é criada na migration 20260622000014_jur_duvidas.sql.
-- Idempotente.
-- =========================================================================

-- Garante a função (caso a 000014 ainda não tenha sido aplicada).
CREATE OR REPLACE FUNCTION public.is_juridico_ativo()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public."EMPREGADOS" e
    WHERE e.auth_user_id = auth.uid()
      AND e."Setor_ERP" = 'JURIDICO'
      AND e."Situação"  = 'Trabalhando'
  );
$$;
REVOKE EXECUTE ON FUNCTION public.is_juridico_ativo() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_juridico_ativo() FROM anon;
GRANT  EXECUTE ON FUNCTION public.is_juridico_ativo() TO authenticated;

-- Garante a tabela de comentários (mesma estrutura do sistema Flask).
CREATE TABLE IF NOT EXISTS public."SISTEMA_JURIDICO_COMENTARIOS" (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_processo text NOT NULL,
  autor           text NOT NULL DEFAULT 'Usuário',
  comentario      text NOT NULL,
  criado_em       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_jur_coment_numero ON public."SISTEMA_JURIDICO_COMENTARIOS"(numero_processo);

-- Acesso (leitura+escrita) p/ authenticated — mesmo padrão das demais tabelas
-- do app e idêntico ao sistema Flask original (que só exigia login). Se quiser
-- restringir escrita ao Jurídico depois, troque a policy _all_auth por
-- _select (USING true) + _write (USING public.is_juridico_ativo()).
DO $$
DECLARE t text; seqname text;
BEGIN
  FOREACH t IN ARRAY ARRAY['SISTEMA_JURIDICORT','SISTEMA_JURIDICORT_dort','SISTEMA_JURIDICO_COMENTARIOS'] LOOP
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=t) THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', t);
      -- Sequência do id (BIGSERIAL/IDENTITY) — necessária p/ INSERT via PostgREST.
      seqname := pg_get_serial_sequence('public."'||t||'"', 'id');
      IF seqname IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seqname);
      END IF;
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t||'_select', t);
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t||'_write', t);
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t||'_all_auth', t);
      EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', t||'_all_auth', t);
    END IF;
  END LOOP;
END $$;

NOTIFY pgrst, 'reload schema';
