name: Notify Discord

on:
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        if: ${{ github.event.pull_request.merged == true }}
        run: |
          AUTHOR="${{ github.event.pull_request.user.login }}"
          MERGER="Iury Silva"

          # Mapeamento de logins -> nomes desejados
          case "$AUTHOR" in
            EduardoJeiel007) AUTHOR="duduzin" ;;
            pablotasuyuki)   AUTHOR="pablero" ;;
            jvperetti)       AUTHOR="jão" ;;
          esac

          MESSAGE="Autorização de PR na branch main por IURYzera\n\n\
          PR criada pelo $AUTHOR\n\n\
          gurizadaaaa, por favor digitem:\n\
          $ git fetch origin main\n\
          $ git rebase origin\n\
          $ git status\n\
          "

          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"$MESSAGE\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}